version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      docker:
          image: circleci/openjdk:11.0.7-jdk-buster
      - maven/test # checkout, build, test, and upload test results